language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/SimpleIR

install:
    - pip install -U platformio
    - platformio lib install 4

script:
    - platformio ci --lib="." --board=uno --board=pro16MHzatmega168